# Generated by Django 5.1.7 on 2025-04-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('matching', 'Matching')], default='multiple_choice', max_length=20, verbose_name='Question Type')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after question is answered', verbose_name='Explanation')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Choice Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Quiz Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quiz_type', models.CharField(choices=[('lesson_quiz', 'Lesson Quiz'), ('module_quiz', 'Module Quiz'), ('final_exam', 'Final Exam'), ('practice', 'Practice Quiz')], default='lesson_quiz', max_length=20, verbose_name='Quiz Type')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (leave empty for unlimited time)', null=True, verbose_name='Time Limit')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum percentage to pass', verbose_name='Passing Score')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed (0 for unlimited)', verbose_name='Maximum Attempts')),
                ('randomize_questions', models.BooleanField(default=True, verbose_name='Randomize Questions Order')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name='Show Correct Answers After Submission')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson', verbose_name='Lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['course', 'module__order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20, verbose_name='Status')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Percentage')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Passed')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('time_spent', models.DurationField(blank=True, null=True, verbose_name='Time Spent')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
                'unique_together': {('quiz', 'student', 'started_at')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Text Answer')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Correct')),
                ('points_earned', models.FloatField(default=0, verbose_name='Points Earned')),
                ('feedback', models.TextField(blank=True, verbose_name='Instructor Feedback')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answered At')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in', to='quiz.choice', verbose_name='Selected Choices')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='quiz.question', verbose_name='Question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='Quiz Attempt')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['attempt', 'question__order'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
